name: Lint

on:
  push:
    branches:
      - master

jobs:
  run-linter:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install packages
        run: npm install --frozen-lockfile

      - name: Run linter
        run: npm run lint